### ISSUE TITLE
Song recognition stops when Mini Player is open, can also cause Apple Music to become unresponsive with certain songs.

### ISSUE THREAD

**Issue by RobinPerson** [PKBeam/AMWin-RP#86]
**Version Info**
Apple Music version 1.4.4.41 (1.1028.10497.0)
AMWin-RP version 1.3.0

**Describe the bug**
With AMWin-RP running, when the Mini Player is opened, it'll minimize the main Apple Music window and the recognized song for the Discord Rich presence will get lost and stop showing. Opening the main Apple Music window will make it recognize the song again, as long as the latest interaction within Apple Music was with the main window it'll keep the song recognized. If the last interaction was with the Mini Player, it'll stop recognizing the song again. (This behavior also happens with other non-main Apple Music windows, including the Status or Equalizer windows).

Additionally, with certain songs, while AMWin-RP is running, after opening the Mini Player and interacting with any of the Apple Music windows can cause Apple Music to freeze and become unresponsive.
The song that triggers this for me is Rebirth by Savant & Julie Elven.

Have the symptoms of this bug already been reported in another issue? 
Not as far as I'm aware.

**Log Files**
[2024-03-01.log](https://github.com/PKBeam/AMWin-RP/files/14466659/2024-03-01.log)

**Comment by PKBeam** [comment]
Likely the same issue as #83

**Comment by PKBeam** [comment]
should be fixed in v1.4.0.

**Comment by RobinPerson** [comment]
Seems that the program becoming unresponsive with some songs while the Mini Player open is still an issue with v1.4.0.

![image](https://github.com/PKBeam/AMWin-RP/assets/33844149/a1d64bb9-49e8-4a0a-8a1c-bd9b434bb28e)
[2024-03-02.log](https://github.com/PKBeam/AMWin-RP/files/14468652/2024-03-02.log)

**Comment by 21mtd** [comment]
can confirm those 2 songs also freezed my AM.

I notice both of them don't have Live Lyrics, maybe that's the cause?
![image](https://github.com/PKBeam/AMWin-RP/assets/75530836/d696d8ee-fab4-47b4-8144-e515d66525ee)

**Comment by Pupalei** [comment]
If it's song related, it's a LOT of songs.  I simply can't use the mini player with any consistency when AMWin is running (AMWin is always running :-).

**Comment by 21mtd** [comment]
> can confirm those 2 songs also freezed my AM.
> 
> I notice both of them don't have Live Lyrics, maybe that's the cause? ![image](https://private-user-images.githubusercontent.com/75530836/320212954-d696d8ee-fab4-47b4-8144-e515d66525ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0OTA1NzgsIm5iZiI6MTcxMjQ5MDI3OCwicGF0aCI6Ii83NTUzMDgzNi8zMjAyMTI5NTQtZDY5NmQ4ZWUtZmFiNC00N2I0LTgxNDQtZTUxNWQ2NjUyNWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDExNDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZGZmOWIyMzM1YmMzYTgzYTg1NjdlOTRiZWRlODhmMDgyNjdlNzQwOTNhNzkzZWYxZGEwYWY2ZjJhNzdlNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v6atGG5NUMurffdj2Aq3aASaFqA8cQsSKqtdKUU9b9M)

It's freezed again, and guess what, a song with no Live Lyrics
https://music.apple.com/us/album/bad-romance/1699077081?i=1699077403

**Comment by Pupalei** [comment]
Nice find!
